AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloudfront origin-request
    
Resources:
    OriginRequestFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: index.handler
            Runtime: nodejs8.10
